apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
        - name: backend-container
          image: dmstjq800/joyuri_backend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080