apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      imagePullSecrets:
        - name: ecr-cred
      containers:
        - name: backend-container
          image: ""
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
