apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: backend-container
          image: dmstjq800/joyuri_front:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000